version: '3'

services:

  web_server:
    image: autn/bagisto-nginx:0.1
    volumes:
      - .:/var/www/app
    working_dir: /var/www/app/
    ports:
      - '9100:443'
    depends_on:
      - db_server
    environment:
      - PHP_MEM_LIMIT=4048M
      - COMPOSER_MEMORY_LIMIT=4048M

  db_server:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: bus
      MYSQL_USER: hoiana
      MYSQL_PASSWORD: hoiana123
      MYSQL_ROOT_PASSWORD: hoianaroot
      MYSQL_ROOT_HOST: '%'
    ports:
      - '9101:3306'

  web_server_non_ssl:
    image: kun391/phpup:1.0
    volumes:
      - .:/var/www/app
    working_dir: /var/www/app/
    ports:
      - '9105:80'
    depends_on:
      - db_server
    environment:
      - PHP_MEM_LIMIT=4048M
      - COMPOSER_MEMORY_LIMIT=4048M
